db:
  image: bankofse/accounts
  ports:
    - "3001:3000"

redis:
  image: redis
  ports:
    - "6379:6379"

disque:
  image: virtualroot/docker-disque
  ports:
    - "7711:7711"
    - "7712:7712"

web:
  build: .
  ports:
    - "80:3000"
  links:
    - db
    - redis
    - disque
  environment:
    DEBUG: cmplxsource:*
